### ISSUE TITLE
Should attributes use camelCase?

### ISSUE THREAD

**Issue by tomayac** [GrapeGreen/web-printing#6]
https://www.w3.org/TR/design-principles/#casing-rules

Compare `attributes['printer-name']` vs. `attributes.printerName`.

**Comment by GrapeGreen** [comment]
I don't have a strong opinion on this: the main reason why I decided for kebab-case was to align as close as possible with [IPP attributes](https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xhtml) and make porting existing code easier. If you believe that alignment with Web Platform Design Principles outweighs this benefit, I'll be happy to follow :)

**Comment by tomayac** [comment]
`Number of web developers using this API` > `Number of web developers aware of IPP`

**Comment by reillyeon** [comment]
If we can do this transformation algorithmically then I'm okay with matching the web platform style. If the spec needs to have a mapping table then I'm less happy with it.

**Comment by GrapeGreen** [comment]
I don't foresee any problems with establishing an automatic mapping from `xxx-yyy-zzz` to `xxxYyyZzz` here.
